(()=>{
if(window.studyUser.role!=='admin')return;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const when=t=>t?new Intl.DateTimeFormat('ko-KR',{dateStyle:'short',timeStyle:'short',timeZone:'Asia/Seoul'}).format(new Date(t)):'아직 접속 전';
const view=document.createElement('section');view.id='adminView';view.className='view';document.querySelector('.content').append(view);
let all=[];
async function api(path){const r=await fetch(path);const d=await r.json();if(!r.ok)throw Error(d.error);return d}
function show(){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v===view));document.querySelectorAll('.nav-item').forEach(v=>v.classList.remove('active'));document.getElementById('sidebar').classList.remove('open');document.getElementById('overlay').classList.remove('show')}
async function list(){show();view.innerHTML='<p role="status">수강생 진도를 불러오는 중입니다.</p>';try{const d=await api('/api/admin');all=d.students;view.innerHTML=`<a class="audit-link" href="/api/assets?name=exam-audit.html" target="_blank" rel="noopener">자료 대조·검수 내역 ↗</a><div class="page-heading"><div><h1>수강생 관리</h1><p>${all.length}명</p></div><button class="text-button" id="adminRefresh">새로고침</button></div><div class="admin-overview"><article><span>학습 시작</span><strong>${all.filter(x=>x.last_seen).length}<small> / ${all.length}명</small></strong></article><article><span>평균 강의 진도</span><strong>${Math.round(all.reduce((s,x)=>s+x.lessons,0)/(all.length*8)*100)}<small>%</small></strong></article><article><span>작성한 과제 답안</span><strong>${all.reduce((s,x)=>s+x.assignmentAnswers,0)}<small>개</small></strong></article></div><label class="admin-search">수강생 찾기<input id="studentSearch" placeholder="이름 또는 학번" type="search"></label><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>수강생</th><th>강의</th><th>과제 완료</th><th>과제 답안</th><th>도전 풀이</th><th>최근 활동</th><th></th></tr></thead><tbody id="studentRows"></tbody></table></div>`;const render=()=>{const term=document.getElementById('studentSearch').value.trim();document.getElementById('studentRows').innerHTML=all.filter(x=>(x.name+x.id).includes(term)).map(x=>`<tr><td><strong>${esc(x.name)}</strong><small>${x.id} · ${x.year}학년</small></td><td>${x.lessons} / 8</td><td>${x.assignments} / 8</td><td>${x.assignmentAnswers} / ${x.assignmentTotal}</td><td>${x.attempted} / ${x.questionTotal}</td><td>${when(x.last_seen)}</td><td><a href="#/admin/${x.id}">상세 보기 →</a></td></tr>`).join('')||'<tr><td colspan="7">검색 결과가 없습니다.</td></tr>'};document.getElementById('studentSearch').oninput=render;document.getElementById('adminRefresh').onclick=list;render()}catch(e){view.innerHTML='<h1>수강생 관리</h1><p>'+esc(e.message)+'</p><button onclick="location.reload()">다시 시도</button>'}}
async function detail(id){show();view.innerHTML='<p role="status">학습 기록을 불러오는 중입니다.</p>';try{const d=await api('/api/admin?id='+id),s=d.summary;view.innerHTML=`<a class="back-button" href="#/admin">← 수강생 목록</a><div class="page-heading"><div><h1>${esc(d.student.name)}</h1><p>${d.student.id} · ${d.student.year}학년 · ${when(d.student.last_seen)}</p></div></div><div class="admin-overview"><article><span>강의 완료</span><strong>${s.lessons}<small> / 8</small></strong></article><article><span>과제 답안</span><strong>${s.assignmentAnswers}<small> / ${s.assignmentTotal}</small></strong></article><article><span>도전 풀이</span><strong>${s.attempted}<small> / ${s.questionTotal}</small></strong></article></div><p class="admin-result-note">도전 확인 ${s.checked} · 정답 표시 ${s.correct} · 이 중 자기평가 ${s.selfAssessed} · 심화 답안 ${s.advanced} / 10</p><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>주차</th><th>강의</th><th>학습 목표</th><th>과제 필수</th><th>전체 답안</th><th>과제 완료</th><th>강의 연습</th><th>도전 확인</th></tr></thead><tbody>${s.weeks.map(w=>`<tr><td>${w.week}주차</td><td>${w.lesson?'완료':'미완료'}</td><td>${w.goals} / ${window.lessonDetails[w.week].objectives.length}</td><td>${w.required} / ${w.requiredTotal}</td><td>${w.answered} / ${w.total}</td><td>${w.assignment?'완료':'미완료'}</td><td>${w.practice}</td><td>${w.challenge}</td></tr>`).join('')}</tbody></table></div><div class="admin-tabs"><button data-tab="assignments" class="active">과제 답안</button><button data-tab="previous">이전 과제 답안</button><button data-tab="practice">강의 연습</button><button data-tab="challenge">도전 풀이</button><button data-tab="advanced">심화</button><button data-tab="activity">활동 기록</button></div><div id="adminAnswers"></div>`;
const answer=(title,prompt,value,key,extra='')=>`<details class="admin-answer"><summary>${esc(title)} <span>${value?.trim()?'작성':'미작성'}</span></summary><p>${esc(prompt)}</p>${extra}<pre>${esc(value||'작성한 답안이 없습니다.')}</pre>${d.updatedAt[key]?'<small>'+when(d.updatedAt[key])+'</small>':''}</details>`;
const tab=name=>{document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));let html='';if(name==='assignments')html=d.assignments.map(a=>`<h2>${a.week}주차</h2>`+a.questions.map((q,i)=>{const key=`response-assignment-${q.uid}`;return answer((i<a.required.length?'필수':i<a.required.length+a.applied.length?'응용':'도전')+' '+(i+1),q.prompt,d.entries[key],key)}).join('')).join('');if(name==='previous')html=d.legacyAssignments.map(a=>{const rows=a.questions.map((q,i)=>{const key=`response-${a.week}-${i+1}`;return d.entries[key]?.trim()?answer('이전 '+(i+1)+'번',q.prompt,d.entries[key],key):''}).join('');return rows?'<h2>'+a.week+'주차</h2>'+rows:''}).join('')||'<p>이전 과제 답안이 없습니다.</p>';if(name==='practice')for(let w=1;w<=8;w++){html+='<h2>'+w+'주차</h2>';window.lessonDetails[w].practice.forEach((q,i)=>{const key=`response-lesson-${w}-${i}`;html+=answer('연습 '+(i+1),q,d.entries[key],key)})}if(name==='challenge')html=d.questions.map(q=>{const key='exam-'+q.uid,v=JSON.parse(d.entries[key]);return answer('문제 '+q.id+' · '+q.week+'주차',q.prompt,v.value,key,'<p>'+esc(v.checked?(v.correct?'정답 표시':'다시 풀기'):'답안 작성 중')+(v.selfAssessed?' · 자기평가':'')+'</p>')}).join('')||'<p>작성한 답안이 없습니다.</p>';if(name==='advanced'){const adv=JSON.parse(d.entries['challenge-advanced-state-v1']||'{}');html=window.advancedProblems.map((q,i)=>answer('심화 '+['I','II','III','IV','V','VI','VII','VIII','IX','X'][i],q.prompt,adv[i],'challenge-advanced-state-v1')).join('')}if(name==='activity')html='<ol class="activity-list">'+d.activity.map(a=>{let detail=a.detail;if(a.kind!=='login'){try{const x=JSON.parse(detail);detail=x.visit?'페이지 열람 · '+x.visit:(x.keys||[]).some(k=>k.includes('complete'))?'완료 상태 변경':'답안·학습 상태 변경'}catch{}}return'<li><span>'+esc(detail)+'</span><time>'+when(a.created_at)+'</time></li>'}).join('')+'</ol>';document.getElementById('adminAnswers').innerHTML=html};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));tab('assignments');
}catch(e){view.innerHTML='<p>'+esc(e.message)+'</p><a href="#/admin">수강생 목록</a>'}}
function route(){const p=location.hash.match(/^#\/admin(?:\/(\d{8}))?$/);if(p)p[1]?detail(p[1]):list()}
window.addEventListener('hashchange',route);route();
})();
