const lessons=[
{week:1,status:'planned',icon:'01',title:'컴퓨터는 어떻게 움직일까?',goal:'입력·처리·저장·출력의 큰 흐름과 2진수의 필요성을 설명합니다.',topics:['컴퓨터 구조','하드웨어 4요소','부팅','2진수'],flow:['컴퓨터의 네 가지 역할','전원을 켠 뒤 운영체제가 준비되는 과정','10진수와 2진수 변환'],example:'온라인 강의를 볼 때 키보드·CPU·RAM·모니터가 각각 어떤 역할을 하는지 연결해 봅니다.',practice:['10진수 13을 8비트 2진수로 바꾸기','RAM·ROM·저장장치를 사용해 부팅 설명하기']},
{week:2,status:'planned',icon:'02',title:'0과 1로 숫자를 담는 법',goal:'같은 비트열이 표현 방식에 따라 다른 값이 되는 이유를 이해합니다.',topics:['정수 표현','2의 보수','부동소수점','ASCII'],flow:['부호 없는 정수와 표현 범위','2의 보수로 음수 표현하기','지수부와 가수부로 실수 표현하기'],example:'8비트 11111011을 부호 없는 수와 2의 보수로 각각 읽고 차이를 비교합니다.',practice:['-13을 8비트 2의 보수로 나타내기','비트 수에 따른 정수 범위 구하기']},
{week:3,status:'planned',icon:'⚡',title:'0과 1이 판단을 만드는 법',goal:'진리표에서 논리식을 만들고 간단한 회로의 동작을 설명합니다.',topics:['논리 게이트','진리표','K-map','가산기','플립플롭'],flow:['AND·OR·NOT 게이트를 일상 조건으로 이해하기','진리표에서 논리식 만들기','K-map으로 식 간소화하기','가산기에서 플립플롭까지 연결하기'],example:'두 입력 중 정확히 하나만 1일 때 출력이 1인 XOR 회로를 진리표로 만든 뒤 논리식으로 옮깁니다.',practice:['출력 조건으로 3입력 진리표 완성하기','4변수 K-map의 인접 항 묶기','조합회로와 순서회로 비교하기']},
{week:4,status:'planned',icon:'📝',title:'중간고사, 아는 것을 점수로 바꾸기',goal:'문제 유형을 구분하고 풀이 과정을 짧고 분명하게 남깁니다.',topics:['범위 연결 복습','기출 분석','시간 배분','오답 정리'],flow:['기출문제를 단원별로 분류하기','표현·회로 문제의 풀이 틀 익히기','제한 시간 안에 모의고사 풀기'],example:'문제를 읽자마자 비트 수·표현 방식·요구 결과를 표시하는 20초 루틴을 적용합니다.',practice:['2025 중간고사 시간 측정 풀이','오답 원인을 개념·계산·조건 누락으로 분류하기']},
{week:5,status:'planned',icon:'🧠',title:'컴퓨터 안에서 명령어가 움직이는 길',goal:'명령어가 메모리에서 CPU로 와 실행되는 흐름을 설명합니다.',topics:['CPU','레지스터','메모리 계층','버스','캐시'],flow:['CPU 내부 구성요소의 역할','fetch-decode-execute 사이클','메모리 계층과 지역성','캐시와 파이프라인'],example:'PC가 가리킨 주소에서 명령어를 가져와 IR에 저장하고 실행하는 과정을 레지스터 변화로 추적합니다.',practice:['PC·IR·MAR·MBR 역할 연결하기','캐시 hit ratio 계산하기']},
{week:6,status:'planned',icon:'🔍',title:'기계어를 읽는 첫날',goal:'짧은 Pep/8 프로그램을 한 줄씩 읽으며 메모리 변화를 추적합니다.',topics:['Pep/8','명령어 형식','주소지정','메모리 추적'],flow:['명령어와 데이터가 함께 저장되는 메모리','연산 코드와 피연산자 읽기','즉시·직접 주소지정 비교','누산기와 메모리 변화 기록'],example:'LDA, ADDA, STA 세 명령을 실행하며 누산기 A와 메모리 값을 표에 기록합니다.',practice:['명령어별 읽는 값과 쓰는 값 표시하기','간단한 입출력 프로그램 추적하기']},
{week:7,status:'planned',icon:'🔁',title:'조건과 반복을 기계어로 옮기기',goal:'if와 while이 분기 명령어로 바뀌는 원리를 설명합니다.',topics:['조건 분기','반복문','C와 어셈블리','코드 추적'],flow:['비교와 상태 비트 확인하기','if-else의 두 경로 추적하기','while의 시작·종료점 찾기','C 코드와 Pep/8 대응하기'],example:'while(i < 3)의 비교·조건 분기·증가·되돌아가기 구조를 화살표로 표시합니다.',practice:['분기 목적지와 실행 순서 기록하기','C 조건문을 Pep/8 흐름도로 바꾸기']},
{week:8,status:'planned',icon:'🏁',title:'기말고사, 흐름을 끝까지 연결하기',goal:'하드웨어와 코드 문제를 구분해 자신만의 풀이 순서를 만듭니다.',topics:['종합 복습','기계어 해독','빈칸 코드','시험 전략'],flow:['하드웨어 역할과 명령어 사이클 복습','기계어·어셈블리 추적 문제 풀이','서술형 핵심어 정리','기말 모의고사'],example:'한 문제에서 메모리 주소, 레지스터, 분기 흐름을 표 하나로 끝까지 추적합니다.',practice:['과년도 기말 유사문항 풀이','시험 직전 한 장 요약 만들기']}
];
lessons.forEach(lesson=>{lesson.icon=''});
const assignmentTimes=['필수 30~40분 · 응용 15~20분','필수 35분 · 도전 20분','필수 40분 · 도전 25분','모의고사 60분 · 오답 30분','필수 35분 · 응용 20분','필수 40분 · 도전 20분','필수 45분 · 도전 25분','모의고사 60분 · 오답 30분'];
const lessonDates=['10월 1일','10월 8일','10월 15일','10월 22일','10월 29일','11월 5일','11월 12일','11월 19일'];
const lessonAnswers=[
['CPU는 연산·제어, 주기억장치는 실행 중 데이터 저장, 입력장치는 데이터 전달, 출력장치는 처리 결과 표현을 담당합니다.','45(10)=101101(2), 0.75(10)=0.11(2), A3(16)=163(10)입니다.','전원을 켜면 ROM의 BIOS가 장치를 점검하고 저장장치의 운영체제를 RAM에 올려 실행합니다.','CPU와 메모리 사이 전송 속도가 전체 성능을 제한하는 현상이며, 캐시 메모리나 하버드 구조로 완화할 수 있습니다.'],
['-37의 절댓값 00100101을 반전하고 1을 더하면 11011011입니다.','같은 부호의 두 수를 더했는데 결과 부호가 달라지면 오버플로입니다.','정규화한 1.x × 2ⁿ에서 부호는 sign, n은 지수, 소수부는 가수에 저장합니다.','ASCII는 제한된 영문 문자 집합이고, 유니코드는 여러 언어 문자를 하나의 체계로 표현합니다.'],
['출력이 1인 행의 최소항을 만들고 OR로 연결합니다.','인접한 1을 1·2·4·8개 단위로 가장 크게 묶은 뒤 변하지 않는 변수만 남깁니다.','반가산기는 입력 2개, 전가산기는 입력 2개와 이전 자리올림을 받아 합과 자리올림을 냅니다.','각 플립플롭의 입력 조건과 현재 Q를 특성표에 대입해 다음 Q를 결정합니다.'],
['시간을 재고 실제 답안지처럼 풀이한 뒤 채점합니다.','틀린 최초 원인을 개념·조건·계산 중 하나로 표시하고 다시 풉니다.','공식만 적지 말고 적용 조건과 대표 예제를 함께 한 장에 정리합니다.'],
['Fetch에서 PC→MAR, 메모리→MBR→IR, 이후 PC 증가와 Decode·Execute 변화를 순서대로 기록합니다.','평균 접근 시간 = 적중률×캐시 시간 + 실패율×(캐시 시간+메모리 시간)입니다.','구조적·데이터·제어 위험으로 나누고 각각 자원 충돌·의존성·분기를 확인합니다.'],
['명령마다 읽는 피연산자, ACC 변화, 쓰는 메모리 값을 한 행씩 기록합니다.','즉시는 명령어 안의 값을 사용하고, 직접은 지정 주소에 저장된 값을 가져옵니다.','입력 명령으로 두 값을 받고 ACC에서 더한 뒤 출력 명령으로 결과를 내보내는 흐름입니다.'],
['조건 비교 뒤 거짓일 때 else 레이블로 분기하고, 참 블록 뒤에는 끝 레이블로 이동합니다.','초기화→조건 검사→본문→증가→조건 검사 순으로 반복하며 거짓이면 종료합니다.','인덱스를 증가시키며 각 원소를 누산기에 더하고 배열 끝에서 결과를 저장합니다.','CALL은 복귀 주소를 스택에 저장하고 PC를 함수 주소로 바꾸며, RET은 스택의 주소를 PC로 복구합니다.'],
['시간 배분표를 먼저 정하고 계산·추적·서술 순서로 실전처럼 풉니다.','각 명령마다 PC, IR, ACC, 피연산자 주소와 메모리 변화를 한 행에 기록합니다.','정의·동작 순서·결과를 나타내는 핵심어 세 개를 답안의 뼈대로 사용합니다.','자주 틀리는 개념, 공식, 추적 순서만 우선순위대로 한 장에 압축합니다.']
];
let currentView='home'; const completed=new Set(JSON.parse(window.studyStore.getItem('comsigae-complete')||'[]'));
const assignmentCompleted=new Set(JSON.parse(window.studyStore.getItem('comsigae-assignment-complete-v2')||'[]'));
const priorLessonsDone=n=>Array.from({length:n-1},(_,i)=>i+1).every(w=>completed.has(w));
const lessonPracticeFilled=n=>window.lessonDetails[n].practice.every((_,i)=>(window.studyStore.getItem(`response-lesson-${n}-${i}`)||'').trim());
function refreshLessonCompletion(n){
 const button=document.querySelector(`[data-complete-week="${n}"]`);
 const count=window.lessonDetails[n].practice.filter((_,i)=>(window.studyStore.getItem(`response-lesson-${n}-${i}`)||'').trim()).length;
 button.disabled=!completed.has(n)&&(!priorLessonsDone(n)||!lessonPracticeFilled(n));
 button.textContent=completed.has(n)?'완료 취소':!priorLessonsDone(n)?`${n-1}주차 완료 후 가능`:!lessonPracticeFilled(n)?`연습 ${count} / ${window.lessonDetails[n].practice.length} 완료`:'이번 주 완료하기';
}
// Keep old progress but remove completions after the first unfinished lesson.
for(let n=1;n<=8;n++)if(!priorLessonsDone(n))completed.delete(n);
window.studyStore.setItem('comsigae-complete',JSON.stringify([...completed]));
const assignmentKey=id=>'response-assignment-'+window.challengeBank[id-1].uid;
function requiredFilled(n){return window.weekAssignments[n-1].required.every(id=>(window.studyStore.getItem(assignmentKey(id))||'').trim())}
const labels={home:'홈',lessons:'주차별 강의',assignments:'과제',resources:'자료실',community:'커뮤니티',challenge:'도전 220제',about:'강의 안내',detail:'강의 상세'};
const viewRoutes={home:'#/',lessons:'#/lessons',assignments:'#/assignments',resources:'#/resources',community:'#/community',challenge:'#/challenge',about:'#/about'};
function go(view,syncRoute=true){currentView=view;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(view+'View').classList.add('active');document.querySelectorAll('.nav-item,.challenge-header-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.getElementById('sidebar').classList.remove('open');document.getElementById('overlay').classList.remove('show');if(syncRoute&&viewRoutes[view]&&location.hash!==viewRoutes[view])history.pushState(null,'',viewRoutes[view]);window.studyStore.visit(location.hash);if(view==='community')loadCommunity();if(view==='challenge')window.challengeApp?.openFromRoute();window.scrollTo({top:0,behavior:'smooth'});}
function renderJourney(){document.getElementById('journey').innerHTML=lessons.map(l=>`<article class="journey-card ${completed.has(l.week)?'complete':'planned'}" data-week="${l.week}"><span class="week-no">${l.week}주차 · ${lessonDates[l.week-1]}</span><h3>${l.title}</h3><p>${l.topics.slice(0,3).join(' · ')}</p></article>`).join('');}
function renderLessons(filter='all'){const list=lessons.filter(l=>filter==='all'||filter==='complete'&&completed.has(l.week)||filter==='planned'&&!completed.has(l.week));document.getElementById('lessonGrid').innerHTML=list.length?list.map(l=>`<article class="lesson-card" data-week="${l.week}"><div class="meta"><span>${l.week}주차</span><span>${lessonDates[l.week-1]}${completed.has(l.week)?' · 완료':''}</span></div><h2>${l.title}</h2><p>${l.goal}</p></article>`).join(''):'<div class="empty">표시할 강의가 없습니다.</div>';}
function renderAssignments(){document.getElementById('assignmentList').innerHTML=lessons.map((l,i)=>`<article class="assignment ${assignmentCompleted.has(l.week)?'done':''}" data-assignment-week="${l.week}"><div><h3>${l.week}주차 과제 · ${l.title}</h3><p>필수 ${window.weekAssignments[l.week-1].required.length}문제 · 응용 ${window.weekAssignments[l.week-1].applied.length}문제 · 도전 ${window.weekAssignments[l.week-1].challenge.length}문제</p></div><div class="assignment-meta"><strong>${lessonDates[i]}</strong><span>과제 보기 →</span></div></article>`).join('');updateProgress();}
function openAssignmentWeek(n,syncRoute=true){
 const l=lessons.find(x=>x.week===Number(n));if(!l)return;const a=window.weekAssignments[l.week-1];
 const group=(title,ids,start)=>`<section class="lesson-section assignment-group"><h2>${title} <small>${ids.length}문제</small></h2><ol start="${start}">${ids.map((id,i)=>{const no=start+i,q=window.challengeBank[id-1];return `<li><div class="assignment-question"><div class="problem-meta"><span class="source-badge">${escapeHtml(title==='도전'?q.source.replace(/ · 응용$/, ' · 도전'):q.source)}</span></div><label><input type="checkbox" data-check="assignment-${l.week}-${no}" disabled><span>${escapeHtml(q.prompt)}</span></label>${window.questionMaterial(q)}<label class="answer-field-label" for="response-${l.week}-${no}">풀이·답안</label><textarea id="response-${l.week}-${no}" class="assignment-response" data-response="assignment-${q.uid}" data-check-key="${l.week}-${no}" rows="4" placeholder="풀이 과정과 답을 작성하세요"></textarea><div class="answer-actions"><button class="answer-toggle" data-assignment-answer="${l.week}-${no}" aria-expanded="false">예시 답안 보기</button></div><div class="practice-answer" id="assignment-answer-${l.week}-${no}">${escapeHtml(q.answer)}${q.explanation?'<p>'+escapeHtml(q.explanation)+'</p>':''}</div></div></li>`}).join('')}</ol></section>`;
 document.getElementById('assignmentDetail').innerHTML=`<section class="detail-hero"><span class="detail-week">${l.week}주차 과제 · ${lessonDates[l.week-1]}</span><h1>${l.title}</h1><div class="scope">필수 ${a.required.length} · 응용 ${a.applied.length} · 도전 ${a.challenge.length}</div><nav class="assignment-jumps"><a href="#requiredSet">필수</a><a href="#appliedSet">응용</a><a href="#challengeSet">도전</a></nav></section><div class="detail-body"><article class="detail-content"><div id="requiredSet">${group('필수',a.required,1)}</div><div id="appliedSet">${group('응용',a.applied,a.required.length+1)}</div><div id="challengeSet">${group('도전',a.challenge,a.required.length+a.applied.length+1)}</div></article><aside class="detail-aside"><h3>과제 진행</h3><p class="required-progress" id="requiredProgress"></p><p id="assignmentAllProgress"></p><button class="primary-button assignment-complete-button" style="width:100%;margin-top:14px" data-complete-assignment="${l.week}">${assignmentCompleted.has(l.week)?'완료 취소':'과제 완료하기'}</button></aside></div>`;
 const completeButton=document.querySelector('.assignment-complete-button');const refreshRequired=()=>{const ids=[...a.required,...a.applied,...a.challenge];const count=a.required.filter(id=>(window.studyStore.getItem(assignmentKey(id))||'').trim()).length,total=ids.filter(id=>(window.studyStore.getItem(assignmentKey(id))||'').trim()).length;document.getElementById('requiredProgress').textContent=`필수 ${count} / ${a.required.length} 작성`;document.getElementById('assignmentAllProgress').textContent=`전체 ${total} / ${ids.length} 작성`;if(count<a.required.length&&assignmentCompleted.has(l.week)){assignmentCompleted.delete(l.week);window.studyStore.setItem('comsigae-assignment-complete-v2',JSON.stringify([...assignmentCompleted]));completeButton.textContent='과제 완료하기'}completeButton.disabled=!assignmentCompleted.has(l.week)&&count<a.required.length};
 document.getElementById('assignmentDetail').querySelectorAll('[data-response]').forEach(field=>{const key=field.dataset.response;field.value=window.studyStore.getItem('response-'+key)||'';const checkbox=document.querySelector(`[data-check="assignment-${field.dataset.checkKey}"]`);checkbox.checked=!!field.value.trim();field.oninput=()=>{checkbox.checked=!!field.value.trim();window.studyStore.setItem('response-'+key,field.value);refreshRequired()}});refreshRequired();
 document.querySelectorAll('.assignment-jumps a').forEach(link=>link.onclick=e=>{e.preventDefault();document.querySelector(link.getAttribute('href')).scrollIntoView({behavior:'smooth'})});
 if(syncRoute&&location.hash!==`#/assignments/${l.week}`)history.pushState(null,'',`#/assignments/${l.week}`);go('assignmentDetail',false);
}
function openWeek(n,syncRoute=true){
  const l=lessons.find(x=>x.week===Number(n));
  const d=window.lessonDetails[l.week];
  const sectionHtml=d.sections.map(section=>`<section class="lesson-section"><h2>${section.title}</h2><p>${section.body}</p>${section.points?`<ul>${section.points.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}${section.steps?`<ol>${section.steps.map(x=>`<li>${x}</li>`).join('')}</ol>`:''}${section.tip?`<div class="exam-tip"><strong>시험 포인트</strong><p>${section.tip}</p></div>`:''}</section>`).join('');
  document.getElementById('lessonDetail').innerHTML=`<section class="detail-hero"><span class="detail-week">${l.week}주차 · ${lessonDates[l.week-1]} 목요일 18:00</span><h1>${l.title}</h1><p>${d.intro}</p><div class="scope"><strong>진도</strong> ${d.scope}</div></section><div class="detail-body"><article class="detail-content"><section class="lesson-section goals"><h2>학습 목표</h2><div class="goal-list">${d.objectives.map((x,i)=>`<label><input type="checkbox" data-check="${l.week}-goal-${i}"> <span>${x}</span></label>`).join('')}</div></section>${sectionHtml}<section class="lesson-section confusing"><h2>자주 헷갈리는 포인트</h2><ul>${d.confusing.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="lesson-section practice-section"><h2>연습</h2><ol>${d.practice.map((x,i)=>`<li><label class="practice-question-label"><input type="checkbox" data-check="lesson-practice-${l.week}-${i}" disabled><span>${x}</span></label><textarea class="assignment-response" data-response="lesson-${l.week}-${i}" data-check-target="lesson-practice-${l.week}-${i}" rows="4" placeholder="여기에 풀이 과정과 답을 작성하세요"></textarea><div class="answer-actions"><button class="answer-toggle" data-answer-toggle="${l.week}-${i}" aria-expanded="false">답 보기</button></div><div class="practice-answer" id="answer-${l.week}-${i}">${lessonAnswers[l.week-1][i]}</div></li>`).join('')}</ol></section></article><aside class="detail-aside"><h3>이번 주 핵심</h3><ul>${l.topics.map(t=>`<li>${t}</li>`).join('')}</ul><button class="primary-button" style="width:100%;margin-top:22px" data-complete-week="${l.week}" ${!completed.has(l.week)&&(!priorLessonsDone(l.week)||!lessonPracticeFilled(l.week))?'disabled':''}>${completed.has(l.week)?'완료 취소':(priorLessonsDone(l.week)?'이번 주 완료하기':`${l.week-1}주차 완료 후 가능`)}</button></aside></div>`;
  document.getElementById('lessonDetail').querySelectorAll('[data-check]').forEach(c=>{c.checked=window.studyStore.getItem('check-'+c.dataset.check)==='1';c.onchange=()=>window.studyStore.setItem('check-'+c.dataset.check,c.checked?'1':'0')});
  document.getElementById('lessonDetail').querySelectorAll('[data-response]').forEach(field=>{field.value=window.studyStore.getItem('response-'+field.dataset.response)||'';const sync=()=>{window.studyStore.setItem('response-'+field.dataset.response,field.value);if(field.dataset.checkTarget){const checkbox=document.querySelector(`[data-check="${field.dataset.checkTarget}"]`);const filled=Boolean(field.value.trim());checkbox.checked=filled;window.studyStore.setItem('check-'+checkbox.dataset.check,filled?'1':'0')}};sync();field.oninput=()=>{sync();if(completed.has(l.week)&&!lessonPracticeFilled(l.week)){for(let w=l.week;w<=8;w++)completed.delete(w);window.studyStore.setItem('comsigae-complete',JSON.stringify([...completed]));updateProgress()}refreshLessonCompletion(l.week)}});refreshLessonCompletion(l.week);
  if(syncRoute&&location.hash!==`#/lessons/${l.week}`)history.pushState(null,'',`#/lessons/${l.week}`);
  go('detail',false);
}
function updateProgress(){document.getElementById('progressText').textContent=`${completed.size} / 8 완료`;document.getElementById('progressBar').style.width=`${completed.size/8*100}%`;renderJourney();renderLessons(document.querySelector('.chip.active')?.dataset.filter||'all');}
function routeFromLocation(){const path=(location.hash||'#/').replace(/^#\/?/,'').replace(/\/$/,'');const lessonMatch=path.match(/^lessons\/([1-8])$/);if(lessonMatch){openWeek(Number(lessonMatch[1]),false);return}const assignmentMatch=path.match(/^assignments\/([1-8])$/);if(assignmentMatch){openAssignmentWeek(Number(assignmentMatch[1]),false);return}if(/^challenge\/advanced\/(?:[1-9]|10)$/.test(path)){go('challenge',false);return}const challengeMatch=path.match(/^challenge\/(\d{1,4})$/);if(challengeMatch){go('challenge',false);window.challengeApp?.open(Number(challengeMatch[1]),false);return}const routes={'':'home',lessons:'lessons',assignments:'assignments',resources:'resources',community:'community',challenge:'challenge',about:'about'};go(routes[path]||'home',false)}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){e.preventDefault();go(nav.dataset.view)}const gw=e.target.closest('[data-go]');if(gw)go(gw.dataset.go);const assignment=e.target.closest('[data-assignment-week]');if(assignment&&!e.target.matches('[data-assignment]'))openAssignmentWeek(assignment.dataset.assignmentWeek);const w=e.target.closest('[data-week],[data-open-week]');if(w)openWeek(w.dataset.week||w.dataset.openWeek);const answer=e.target.closest('[data-answer-toggle]');if(answer){const panel=document.getElementById('answer-'+answer.dataset.answerToggle);const open=panel.classList.toggle('revealed');answer.textContent=open?'답 가리기':'답 보기';answer.setAttribute('aria-expanded',String(open))}const assignmentAnswer=e.target.closest('[data-assignment-answer]');if(assignmentAnswer){const panel=document.getElementById('assignment-answer-'+assignmentAnswer.dataset.assignmentAnswer);const open=panel.classList.toggle('revealed');assignmentAnswer.textContent=open?'예시 답안 가리기':'예시 답안 보기';assignmentAnswer.setAttribute('aria-expanded',String(open))}const done=e.target.closest('[data-complete-week]');if(done){const n=Number(done.dataset.completeWeek);if(done.disabled||(!completed.has(n)&&(!priorLessonsDone(n)||!lessonPracticeFilled(n))))return;if(completed.has(n)){for(let w=n;w<=8;w++)completed.delete(w)}else completed.add(n);window.studyStore.setItem('comsigae-complete',JSON.stringify([...completed]));renderAssignments();location.hash.startsWith('#/assignments/')?openAssignmentWeek(n):openWeek(n)}const assignmentDone=e.target.closest('[data-complete-assignment]');if(assignmentDone){const n=Number(assignmentDone.dataset.completeAssignment);if(assignmentDone.disabled||(!assignmentCompleted.has(n)&&!requiredFilled(n)))return;assignmentCompleted.has(n)?assignmentCompleted.delete(n):assignmentCompleted.add(n);window.studyStore.setItem('comsigae-assignment-complete-v2',JSON.stringify([...assignmentCompleted]));renderAssignments();openAssignmentWeek(n)}const chip=e.target.closest('[data-filter]');if(chip){document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));chip.classList.add('active');renderLessons(chip.dataset.filter)}});
document.getElementById('menuButton').onclick=()=>{document.getElementById('sidebar').classList.add('open');document.getElementById('overlay').classList.add('show')};document.getElementById('overlay').onclick=()=>{document.getElementById('sidebar').classList.remove('open');document.getElementById('overlay').classList.remove('show')};document.getElementById('backButton').onclick=()=>go('lessons');
document.getElementById('assignmentBackButton').onclick=()=>go('assignments');
const communityForm=document.getElementById('communityForm');
const communityList=document.getElementById('communityList');
function escapeHtml(value){const el=document.createElement('div');el.textContent=value??'';return el.innerHTML}
function formatPostDate(value){const date=new Date(value);return new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(date)}
async function loadCommunity(){communityList.innerHTML='<p class="muted">게시글을 불러오는 중입니다.</p>';try{const response=await fetch('/api/posts');const data=await response.json();if(!response.ok)throw new Error();communityList.innerHTML=data.posts.length?data.posts.map(post=>`<article class="community-post"><div class="post-meta"><span class="post-category">${escapeHtml(post.category)}</span><span>${escapeHtml(post.author)} · ${formatPostDate(post.createdAt)}</span></div><h2>${escapeHtml(post.title)}</h2><p>${escapeHtml(post.content).replace(/\n/g,'<br>')}</p></article>`).join(''):'<div class="community-empty"><strong>아직 게시글이 없어요.</strong><p>첫 질문이나 의견을 남겨보세요.</p></div>'}catch{communityList.innerHTML='<div class="community-empty"><strong>게시글을 불러오지 못했어요.</strong><p>잠시 뒤 다시 시도해 주세요.</p></div>'}}
document.getElementById('writePostButton').onclick=()=>{communityForm.hidden=false;document.getElementById('postTitle').focus()};
document.getElementById('cancelPostButton').onclick=()=>{communityForm.hidden=true;communityForm.reset()};
document.getElementById('postAnonymous').onchange=e=>{const input=document.getElementById('postAuthor');input.disabled=e.target.checked;if(e.target.checked)input.value=''};
communityForm.onsubmit=async e=>{e.preventDefault();const message=document.getElementById('postMessage');const submit=communityForm.querySelector('[type="submit"]');submit.disabled=true;message.textContent='등록 중…';try{const response=await fetch('/api/posts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({category:document.getElementById('postCategory').value,author:document.getElementById('postAuthor').value,anonymous:document.getElementById('postAnonymous').checked,title:document.getElementById('postTitle').value,content:document.getElementById('postContent').value})});const data=await response.json();if(!response.ok)throw new Error(data.error);communityForm.reset();communityForm.hidden=true;message.textContent='';await loadCommunity()}catch(error){message.textContent=error.message||'등록하지 못했습니다.'}finally{submit.disabled=false}};
window.addEventListener('popstate',routeFromLocation);window.addEventListener('hashchange',routeFromLocation);
renderJourney();renderLessons();renderAssignments();routeFromLocation();
