(async()=>{
 let session;try{const r=await fetch('/api/session');if(r.status===401){location.replace('/login.html'+location.hash);return}if(!r.ok)throw Error();session=await r.json()}catch{document.body.innerHTML='<main style="padding:48px"><h1>학습 정보를 불러오지 못했어요.</h1><button onclick="location.reload()">다시 시도</button></main>';return}
 const entries=session.entries,changes={};let timer,flight=null,visit=null,failed=false;
 const notice=document.createElement('div');notice.id='saveError';notice.setAttribute('role','alert');notice.hidden=true;document.body.append(notice);
 const showError=message=>{failed=true;notice.hidden=false;notice.textContent=message+' ';const retry=document.createElement('button');retry.textContent='다시 시도';retry.onclick=()=>flush();notice.append(retry)};
 async function flush(){clearTimeout(timer);if(flight){await flight;if(Object.keys(changes).length||visit)return flush();return !failed}if(!Object.keys(changes).length&&!visit)return true;const batch={...changes},v=visit;for(const k of Object.keys(batch))delete changes[k];visit=null;
 flight=(async()=>{try{const r=await fetch('/api/progress',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({changes:batch,visit:v}),keepalive:JSON.stringify(batch).length<55000});if(r.status===401){showError('로그인이 만료되었습니다. 새 창에서 다시 로그인한 뒤 저장해 주세요.');const login=document.createElement('a');login.href='/login.html';login.target='_blank';login.textContent='로그인';notice.append(login);throw Error('expired')}const data=await r.json();if(!r.ok)throw Error(data.error||'저장하지 못했습니다.');failed=false;notice.hidden=true;return true}catch(e){for(const[k,value]of Object.entries(batch))if(!(k in changes))changes[k]=value;if(e.message!=='expired')showError(e.message||'연결이 끊겨 답안을 저장하지 못했습니다.');return false}finally{flight=null}})();return flight;}
 window.studyUser=session.user;
 window.studyStore={getItem:k=>entries[k]??null,setItem(k,v){v=String(v);if(entries[k]===v)return;entries[k]=v;changes[k]=v;clearTimeout(timer);timer=setTimeout(flush,650)},visit(v){if(visit===v)return;visit=v;clearTimeout(timer);timer=setTimeout(flush,650)},flush};
 window.addEventListener('beforeunload',e=>{if(Object.keys(changes).length||flight){flush();e.preventDefault();e.returnValue=''}});document.addEventListener('visibilitychange',()=>{if(document.hidden)flush()});window.addEventListener('online',flush);
 const footer=document.querySelector('.sidebar-footer');const userMenu=document.createElement('div');userMenu.className='account-menu';userMenu.innerHTML='<span></span><button type="button">로그아웃</button>';userMenu.querySelector('span').textContent=session.user.name;footer.append(userMenu);userMenu.querySelector('button').onclick=async()=>{if(!await flush())return;const r=await fetch('/api/auth/logout',{method:'POST'});if(r.ok)location.replace('/login.html')};
 if(session.user.role==='admin'&&session.user.id==='20253307'){const link=document.createElement('a');link.href='#/admin';link.className='admin-link';link.textContent='수강생 관리';footer.prepend(link)}
 for(const name of ['lesson-content.js','advanced-challenge.js','question-bank.js','exam-ui.js','assignments.js','app.js','admin.js'])await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='/api/assets?name='+name;script.onload=resolve;script.onerror=reject;document.body.append(script)});
 const author=document.getElementById('postAuthor');author.value=session.user.name;author.readOnly=true;const anon=document.getElementById('postAnonymous');anon.onchange=()=>{author.disabled=anon.checked;author.value=anon.checked?'':session.user.name};
})();
