(function(){
const topics=['2진수 변환','16진수 변환','2의 보수','비트와 용량','논리회로','CPU와 레지스터','메모리','부팅','컴퓨터 구조','컴퓨터 역사','부동소수점','순서논리회로','Pep/8','분기와 반복','종합 기출'];
const state=JSON.parse(localStorage.getItem('challenge-1000-state-v3')||'{}');
let current=Number(localStorage.getItem('challenge-1000-current-v3')||1),filtered=[];
const pad=(n,bits)=>n.toString(2).padStart(bits,'0');
function mcq(id,topic,prompt,answer,pool,explanation,difficulty){const options=[answer,...pool.filter(x=>x!==answer)].slice(0,4).sort((a,b)=>((id*(a.length+3))%11)-((id*(b.length+3))%11));return{id,topic,prompt,answer:String(answer),options,explanation,difficulty}}
function make(id){const group=Math.floor((id-1)/100),i=(id-1)%100+1,difficulty=i<=40?'초급':i<=75?'중급':'상급';let n;
if(group===0){n=9+i*3;const mode=i%5;if(mode===0)return{id,topic:topics[group],difficulty,prompt:`10진수 ${n}을 2진수로 변환하세요.`,answer:n.toString(2),explanation:`2로 나눈 나머지를 역순으로 읽으면 ${n.toString(2)}입니다.`};if(mode===1)return{id,topic:topics[group],difficulty,prompt:`2진수 ${n.toString(2)}를 10진수로 해석하세요.`,answer:String(n),explanation:`각 자리의 2의 거듭제곱을 더하면 ${n}입니다.`};if(mode===2)return{id,topic:topics[group],difficulty,prompt:`${n}을 8비트로 저장할 때 앞에 추가되는 0의 개수는?`,answer:String(8-n.toString(2).length),explanation:`${n}=${n.toString(2)}이므로 8비트까지 ${8-n.toString(2).length}개의 0이 필요합니다.`};if(mode===3)return mcq(id,topics[group],`${n.toString(2)}(2)보다 정확히 1 큰 2진수는?`,(n+1).toString(2),[(n-1).toString(2),(n+2).toString(2),(n+4).toString(2)],`이진수에 1을 더한 결과는 ${(n+1).toString(2)}입니다.`,difficulty);return{id,topic:topics[group],difficulty,prompt:`2진수 ${n.toString(2)}에서 1의 개수를 입력하세요.`,answer:String([...n.toString(2)].filter(x=>x==='1').length),explanation:`비트열의 1을 직접 세면 됩니다.`}}
if(group===1){n=30+i*5;const hex=n.toString(16).toUpperCase(),mode=i%5;if(mode===0)return{id,topic:topics[group],difficulty,prompt:`10진수 ${n}을 16진수로 변환하세요.`,answer:hex,explanation:`16으로 나눈 몫과 나머지를 사용하면 ${hex}(16)입니다.`};if(mode===1)return{id,topic:topics[group],difficulty,prompt:`16진수 ${hex}를 10진수로 변환하세요.`,answer:String(n),explanation:`각 자리에 16의 거듭제곱을 곱해 더하면 ${n}입니다.`};if(mode===2)return{id,topic:topics[group],difficulty,prompt:`16진수 ${hex}를 2진수로 바꿀 때 필요한 최소 비트 수는?`,answer:String(hex.length*4),explanation:`16진수 한 자리는 2진수 4비트와 대응합니다.`};if(mode===3)return mcq(id,topics[group],`2진수 ${pad(n,8)}와 같은 16진수는?`,hex,[n-1,n+1,n+16].map(x=>x.toString(16).toUpperCase()),`4비트씩 묶으면 ${hex}입니다.`,difficulty);return{id,topic:topics[group],difficulty,prompt:`16진수 ${hex}의 마지막 한 자리를 10진수로 해석하세요.`,answer:String(parseInt(hex.slice(-1),16)),explanation:`마지막 자리 ${hex.slice(-1)}의 값은 ${parseInt(hex.slice(-1),16)}입니다.`}}
if(group===2){n=(i%100)+1;const signed=256-n,mode=i%5;if(mode===0)return{id,topic:topics[group],difficulty,prompt:`-${n}을 8비트 2의 보수로 표현하세요.`,answer:pad(signed,8),explanation:`절댓값을 반전하고 1을 더하면 ${pad(signed,8)}입니다.`};if(mode===1)return{id,topic:topics[group],difficulty,prompt:`8비트 2의 보수 ${pad(signed,8)}를 10진수로 해석하세요.`,answer:String(-n),explanation:`반전 후 1을 더해 절댓값 ${n}을 얻으므로 -${n}입니다.`};if(mode===2){const bits=4+(i%5);return{id,topic:topics[group],difficulty,prompt:`${bits}비트 2의 보수의 최솟값은?`,answer:String(-(2**(bits-1))),explanation:`최솟값은 -2^(n-1)입니다.`}}if(mode===3)return mcq(id,topics[group],`8비트 계산 ${120-(i%8)} + ${20+(i%8)}에서 발생하는 현상은?`,'오버플로',['정상 계산','언더플로','캐시 미스'],`양수의 합이 127을 넘어 오버플로가 발생합니다.`,difficulty);return{id,topic:topics[group],difficulty,prompt:`8비트 2의 보수에서 -1의 비트열은?`,answer:'11111111',explanation:`모든 비트가 1이면 2의 보수에서 -1입니다.`}}
if(group===3){const mode=i%5,n=(i+1)*64;if(mode===0)return{id,topic:topics[group],difficulty,prompt:`${n} byte는 몇 bit인가요?`,answer:String(n*8),explanation:`1 byte=8 bit이므로 ${n*8} bit입니다.`};if(mode===1)return{id,topic:topics[group],difficulty,prompt:`${n*8} bit는 몇 byte인가요?`,answer:String(n),explanation:`8로 나누면 ${n} byte입니다.`};if(mode===2)return{id,topic:topics[group],difficulty,prompt:`${i+1} KiB는 몇 byte인가요?`,answer:String((i+1)*1024),explanation:`1 KiB=1024 byte입니다.`};if(mode===3)return{id,topic:topics[group],difficulty,prompt:`주소선이 ${8+(i%8)}개라면 구분 가능한 주소 개수는?`,answer:String(2**(8+i%8)),explanation:`n개의 주소선은 2^n개 주소를 구분합니다.`};return mcq(id,topics[group],`용량은 크지만 CPU에서 가장 멀고 느린 것은?`,'SSD',['레지스터','캐시','RAM'],`일반적인 계층은 레지스터→캐시→RAM→SSD 순입니다.`,difficulty)}
if(group===4){const gates=[['AND','두 입력이 모두 1일 때만 1'],['OR','하나 이상의 입력이 1이면 1'],['XOR','두 입력이 서로 다르면 1'],['NOT','입력을 반전']];const g=gates[i%4];return mcq(id,topics[group],`설명이 “${g[1]}”인 논리 게이트는?`,g[0],gates.map(x=>x[0]),`${g[0]} 게이트의 정의입니다.`,difficulty)}
if(group===5){const rows=[['PC','다음에 실행할 명령어 주소'],['IR','현재 실행 중인 명령어'],['MAR','접근할 메모리 주소'],['MBR','메모리와 주고받는 데이터'],['ACC','연산 결과']];const r=rows[i%5];return mcq(id,topics[group],`“${r[1]}”를 저장하는 레지스터는?`,r[0],rows.map(x=>x[0]),`${r[0]}는 ${r[1]}를 저장합니다.`,difficulty)}
if(group===6){const rows=[['레지스터','가장 빠르고 용량이 가장 작음'],['캐시','CPU와 RAM의 속도 차이를 완화'],['RAM','실행 중인 프로그램과 데이터 저장'],['SSD','전원이 꺼져도 데이터 보존']];const r=rows[i%4];return mcq(id,topics[group],`“${r[1]}”에 해당하는 저장장치는?`,r[0],rows.map(x=>x[0]),`${r[0]}의 핵심 역할은 ${r[1]}입니다.`,difficulty)}
if(group===7){const seq=['BIOS 실행','POST 수행','부팅 장치 확인','OS를 RAM에 적재'];const target=seq[i%4];return mcq(id,topics[group],`부팅 과정에서 “${target}”의 올바른 순서는?`,String(seq.indexOf(target)+1),['1','2','3','4'],`기본 순서는 BIOS → POST → 부팅 장치 확인 → OS 적재입니다.`,difficulty)}
if(group===8){const rows=[['폰 노이만 구조','명령어와 데이터를 같은 메모리에 저장'],['하버드 구조','명령어와 데이터 메모리·버스를 분리'],['파이프라이닝','여러 명령 단계를 겹쳐 실행'],['캐시','자주 쓰는 데이터를 CPU 가까이에 저장']];const r=rows[i%4];return mcq(id,topics[group],`“${r[1]}”에 해당하는 개념은?`,r[0],rows.map(x=>x[0]),`${r[0]}의 핵심 정의입니다.`,difficulty)}
if(group===10){const rows=[['부호 비트','수의 양수·음수 결정'],['지수부','소수점의 위치 결정'],['가수부','유효 숫자 저장'],['hidden bit','정규화된 맨 앞의 1을 생략']];const r=rows[i%4];return i%2?mcq(id,topics[group],`부동소수점에서 “${r[1]}” 역할을 하는 부분은?`,r[0],rows.map(x=>x[0]),`${r[0]}는 ${r[1]} 역할을 합니다.`,difficulty):mcq(id,topics[group],`${r[0]}의 역할로 옳은 것은?`,r[1],rows.map(x=>x[1]),`${r[0]}는 ${r[1]} 역할을 합니다.`,difficulty)}
if(group===11){const rows=[['SR 래치','S와 R로 상태를 설정·초기화'],['D 플립플롭','한 비트 데이터를 클록에 맞춰 저장'],['JK 플립플롭','J=K=1일 때 상태 반전'],['T 플립플롭','T=1일 때 상태 반전'],['비동기 카운터','앞단 출력이 다음 단의 클록 역할']];const r=rows[i%5];return i%2?mcq(id,topics[group],`“${r[1]}”에 해당하는 순서회로는?`,r[0],rows.map(x=>x[0]),`${r[0]}: ${r[1]}.`,difficulty):mcq(id,topics[group],`${r[0]}의 핵심 동작은?`,r[1],rows.map(x=>x[1]),`${r[0]}: ${r[1]}.`,difficulty)}
if(group===12){const rows=[['LDA','메모리 값을 누산기에 적재'],['STA','누산기 값을 메모리에 저장'],['ADDA','누산기에 값을 더함'],['SUBA','누산기에서 값을 뺌'],['DECI','10진 정수 입력'],['DECO','10진 정수 출력'],['CHARI','문자 입력'],['STRO','문자열 출력']];const r=rows[i%8];return i%2?mcq(id,topics[group],`Pep/8에서 “${r[1]}” 명령어는?`,r[0],rows.map(x=>x[0]),`${r[0]}는 ${r[1]} 명령입니다.`,difficulty):mcq(id,topics[group],`Pep/8 명령어 ${r[0]}의 기능은?`,r[1],rows.map(x=>x[1]),`${r[0]}는 ${r[1]} 명령입니다.`,difficulty)}
if(group===13){const rows=[['BREQ','Z=1이면 분기'],['BRNE','Z=0이면 분기'],['BRLT','비교 결과가 작으면 분기'],['BRGT','비교 결과가 크면 분기'],['BR','무조건 분기'],['CALL','복귀 주소를 저장하고 함수 호출'],['RET','저장한 주소로 복귀']];const r=rows[i%7];return i%2?mcq(id,topics[group],`“${r[1]}”에 필요한 Pep/8 명령은?`,r[0],rows.map(x=>x[0]),`${r[0]}는 ${r[1]} 기능을 합니다.`,difficulty):mcq(id,topics[group],`${r[0]} 명령의 역할은?`,r[1],rows.map(x=>x[1]),`${r[0]}는 ${r[1]} 기능을 합니다.`,difficulty)}
if(group===14){const qs=[
['Pep/8 코드 `D1 001D`가 주소 001D의 바이트 81을 읽은 뒤 `F1 0009`를 실행했습니다. 주소 0009에 저장되는 값은?','81','F1은 A 레지스터의 하위 바이트를 지정 주소에 저장하므로 0009의 값은 81이 됩니다.'],
['Pep/8에서 `C1 0017`을 실행할 때 주소 0017부터 두 바이트가 `00 05`라면 A 레지스터의 값은?','0005','C1은 직접 주소지정으로 한 워드를 A에 적재합니다.'],
['A=0005인 상태에서 메모리 0019의 워드가 0003이고 `ANDA 0019,d`를 실행했습니다. A의 16진수 결과는?','0001','0005 AND 0003은 비트 단위 연산 결과 0001입니다.'],
['A=0001인 상태에서 `CPA 0030,i` 후 `BRLT less`를 실행하면 분기하나요? 예 또는 아니오로 답하세요.','예','1은 즉시값 0x0030(48)보다 작으므로 N 조건이 성립해 BRLT가 분기합니다.'],
['`LDA num,d` → `ADDA 10,i` → `STA sum,d` 실행 전 num=7이라면 sum에 저장되는 값은?','17','A에 7을 적재하고 즉시값 10을 더한 뒤 sum에 저장합니다.'],
['0을 입력하면 종료하는 반복문에서 `LDA input,d`와 `CPA 0,i` 다음에 들어갈 조건 분기 명령은?','BREQ','비교 결과가 같아 Z=1일 때 종료해야 하므로 BREQ를 사용합니다.'],
['문자 ch가 대문자인지 검사하려고 `CPA \'A\',i` 뒤에서 A보다 작은 문자를 else로 보낼 때 사용할 명령은?','BRLT','비교 대상보다 작은 경우 분기하는 BRLT가 필요합니다.'],
['명령어 인출 과정에서 PC가 가리키는 메모리 주소를 먼저 전달받는 레지스터는?','MAR','PC의 주소가 MAR로 전달되고, 읽은 명령어는 MBR을 거쳐 IR로 이동합니다.'],
['메모리에서 읽은 명령어가 MBR을 거쳐 최종적으로 저장되는 레지스터는?','IR','현재 해독·실행할 명령어는 IR에 저장됩니다.'],
['캐시 hit time이 1사이클, miss rate가 5%, miss penalty가 20사이클일 때 평균 접근 시간은 몇 사이클인가요?','2','AMAT=1+0.05×20=2사이클입니다.'],
['기본 CPI가 1이고 명령어의 20%에서 2사이클의 stall이 발생하면 평균 CPI는?','1.4','평균 CPI=1+0.20×2=1.4입니다.'],
['`LDA value,d`와 `LDA value,i` 중 메모리의 value 번지에 저장된 값을 읽는 명령을 쓰세요.','LDA value,d','d는 피연산자를 주소로 해석하는 직접 주소지정이고 i는 값 자체를 사용하는 즉시 주소지정입니다.'],
['Pep/8에서 정수 25를 입력받아 메모리 num에 저장할 때 사용하는 명령은?','DECI num,d','DECI는 10진 정수를 입력받아 지정 메모리에 저장합니다.'],
['16비트 2의 보수 값 FF9C를 10진수로 해석하세요.','-100','0xFF9C의 unsigned 값 65436에서 65536을 빼면 -100입니다.'],
['big-endian 방식의 연속된 두 바이트가 `12 34`일 때 한 워드의 16진수 값은?','1234','상위 바이트 12가 낮은 주소에 먼저 저장되므로 워드는 0x1234입니다.'],
['서브루틴 실행 뒤 호출한 위치로 돌아가기 위해 CALL과 짝으로 사용하는 명령은?','RET','CALL은 복귀 주소를 저장하고 RET은 그 주소로 돌아갑니다.'],
['16비트 2의 보수에서 7FFF와 0001을 더하면 발생하는 현상은?','오버플로','최대 양수 32767에 1을 더해 표현 범위를 넘습니다.'],
['`CPA limit,d` 실행 결과 A와 limit가 같을 때 분기하는 Pep/8 명령은?','BREQ','두 값이 같으면 Z 플래그가 1이 되어 BREQ가 분기합니다.'],
['count=3에서 시작해 매 반복마다 1을 빼고 count가 0이 아니면 반복한다면 반복 본문은 총 몇 번 실행되나요?','3','count가 3, 2, 1인 세 번 실행된 뒤 0에서 종료합니다.'],
['캐시 접근 200회 중 hit가 170회라면 hit ratio를 백분율로 쓰세요.','85%','170÷200×100=85%입니다.'],
['명령어와 데이터를 서로 다른 메모리와 버스로 분리해 동시에 접근할 수 있게 하는 구조는?','하버드 구조','하버드 구조는 명령어와 데이터 경로를 분리해 단일 버스 경쟁을 줄입니다.']
];const q=qs[(i-1)%qs.length];return{id,topic:topics[group],difficulty:'상급',prompt:q[0],answer:q[1],explanation:q[2]}}
const rows=[['ABC','최초의 전자식 특수 목적 컴퓨터'],['ENIAC','최초의 범용 전자식 컴퓨터'],['폰 노이만','내장형 프로그램 개념 제안'],['UNIVAC-I','최초의 상용 컴퓨터']];const r=rows[i%4];return mcq(id,topics[group],`“${r[1]}”에 해당하는 것은?`,r[0],rows.map(x=>x[0]),`${r[0]}: ${r[1]}.`,difficulty)}
const examSeeds=[
['컴퓨터 역사','중급','ABC와 비교했을 때 ENIAC의 가장 큰 장점을 한 단어로 쓰세요.','범용성','ABC는 특수 목적, ENIAC은 여러 문제를 프로그램할 수 있는 범용 컴퓨터입니다.','2025 글미 중간 기출'],
['컴퓨터 구조','초급','컴퓨터 하드웨어의 기본 구성 요소는 모두 몇 부분인가요? 숫자만 입력하세요.','4','CPU, 주기억장치, 입력장치, 출력장치의 네 부분입니다.','2025 글미 중간 기출'],
['부팅','중급','ROM의 프로그램이 저장장치의 운영체제를 RAM으로 불러오는 과정을 무엇이라고 하나요?','부팅','부팅은 운영체제를 주기억장치로 적재해 실행 가능한 상태로 만드는 과정입니다.','2025 글미 중간 기출'],
['컴퓨터 구조','상급','CPU와 메모리 사이의 전송 속도가 전체 성능을 제한하는 현상은?','폰 노이만 병목','폰 노이만 병목 현상입니다.','2025 글미 중간 기출'],
['2의 보수','중급','4비트 2의 보수 표현의 최솟값을 숫자로 입력하세요.','-8','n비트 2의 보수 범위는 -2^(n-1)부터 2^(n-1)-1입니다.','2025 글미 중간 기출'],
['비트와 용량','중급','Python에서 0.1+0.2==0.3의 결과를 True 또는 False로 입력하세요.','FALSE','0.1과 0.2는 이진 부동소수점으로 정확히 표현되지 않아 False입니다.','2025 글미 중간 기출'],
['논리회로','중급','A=0, B=1일 때 (A+B)·A′·(A+B)의 결과는?','1','(0+1)·1·(0+1)=1입니다.','2025 글미 중간 기출'],
['논리회로','중급','ripple-carry adder의 최대 단점은 carry 전달로 인한 무엇인가요?','지연','자리올림이 단계마다 전달되어 지연이 누적됩니다.','2025 글미 중간 기출'],
['논리회로','상급','SR 래치에서 일반적으로 사용을 금지하는 입력 조합을 S,R 순서로 쓰세요.','11','S=R=1은 출력의 상보 관계를 깨뜨려 금지 상태입니다.','2025 글미 중간 기출'],
['컴퓨터 역사','초급','내장형 프로그램 개념을 최초로 제안한 사람은?','폰 노이만','John von Neumann이 제안했습니다.','2025 미경 중간 기출'],
['컴퓨터 역사','중급','Relay 다음, Transistor 이전에 사용된 하드웨어 소자는?','진공관','소자 변천은 Relay→진공관→Transistor→IC→VLSI입니다.','2025 미경 중간 기출'],
['논리회로','중급','3비트로 표현 가능한 소수의 개수는?','4','0~7 중 소수는 2,3,5,7로 네 개입니다.','2025 미경 중간 기출'],
['CPU와 레지스터','중급','접근할 메모리 주소를 저장하는 레지스터는?','MAR','MAR은 Memory Address Register입니다.','2025 미경 기말 기출'],
['CPU와 레지스터','중급','메모리와 주고받는 데이터를 임시 저장하는 레지스터는?','MBR','MBR은 Memory Buffer Register입니다.','2025 미경 기말 기출'],
['CPU와 레지스터','상급','명령어 수행 사이클의 세 단계를 쉼표로 구분해 쓰세요.','인출,해독,실행','Fetch, Decode, Execute의 세 단계입니다.','2025 미경 기말 기출'],
['메모리','중급','캐시에서 원하는 데이터를 찾은 비율을 무엇이라고 하나요?','히트율','hit ratio 또는 적중률이라고 합니다.','2025 미경 기말 기출'],
['메모리','상급','내용으로 데이터를 검색하는 메모리 방식을 영어로 쓰세요.','ASSOCIATIVE MEMORY','캐시는 주소뿐 아니라 내용 기반 검색이 가능한 associative memory 특성을 활용합니다.','2025 미경 기말 기출'],
['CPU와 레지스터','중급','파이프라인은 여러 명령어의 처리 단계를 어떻게 실행하나요?','중첩','각 명령어의 단계를 겹쳐 실행해 처리량을 높입니다.','2025 미경 기말 기출']
];
const weekGroups={1:[9,7,8,0,1,3],2:[2,10,0,1,3],3:[4,11],4:[0,1,2,4,10,11,9],5:[5,6,8],6:[12,5,6],7:[13,12,5],8:[14,12,13,5,6,8]};
const seedWeek=topic=>topic==='논리회로'?3:topic==='2의 보수'||topic==='비트와 용량'?2:topic==='CPU와 레지스터'||topic==='메모리'?5:1;
const questions=[];for(let week=1;week<=8;week++){const seeds=examSeeds.filter(x=>seedWeek(x[0])===week);for(let slot=0;slot<125;slot++){const id=questions.length+1;if(slot<seeds.length){const [topic,difficulty,prompt,answer,explanation,source]=seeds[slot];questions.push({id,week,topic,difficulty,prompt,answer,explanation,source,sourceType:'기출'});continue}const groups=weekGroups[week],group=groups[(slot-seeds.length)%groups.length],turn=Math.floor((slot-seeds.length)/groups.length)+1;const q=make(group*100+turn);q.id=id;q.week=week;const cycle=slot%10;if(cycle<4){q.source=week===4||week===8?'2025 기출 변형':'주차별 기출 유형 변형';q.sourceType='기출 변형'}else if(cycle<7){q.source='주교재·부교재 기반';q.sourceType='교재 기반'}else{q.source='멘토 직접 제작';q.sourceType='직접 제작'}questions.push(q)}}
function save(){localStorage.setItem('challenge-1000-state-v3',JSON.stringify(state));localStorage.setItem('challenge-1000-current-v3',String(current))}
function normalize(v){return String(v).trim().replace(/\s+/g,'').toUpperCase()}
function initFilters(){const select=document.getElementById('challengeTopic');if(!select||select.options.length)return;select.innerHTML='<option value="all">전체</option>'+topics.map(t=>`<option>${t}</option>`).join('');['challengeWeek','challengeTopic','challengeDifficulty','challengeSource','challengeStatus'].forEach(id=>document.getElementById(id).onchange=()=>{filter();renderIndex()});document.getElementById('challengeRandom').onclick=()=>{filter();const q=filtered[Math.floor(Math.random()*filtered.length)];if(q)open(q.id)}}
function filter(){const week=document.getElementById('challengeWeek').value,topic=document.getElementById('challengeTopic').value,diff=document.getElementById('challengeDifficulty').value,source=document.getElementById('challengeSource').value,status=document.getElementById('challengeStatus').value;filtered=questions.filter(q=>(week==='all'||q.week===Number(week))&&(topic==='all'||q.topic===topic)&&(diff==='all'||q.difficulty===diff)&&(source==='all'||q.sourceType===source)&&(status==='all'||status==='unsolved'&&!state[q.id]||status==='correct'&&state[q.id]?.correct||status==='wrong'&&state[q.id]&&!state[q.id].correct));document.getElementById('challengeCount').textContent=`${filtered.length}개`}
function renderIndex(){const grid=document.getElementById('challengeNumberGrid');grid.innerHTML=filtered.map(q=>`<button data-challenge-id="${q.id}" class="${q.id===current?'current':''} ${state[q.id]?.correct?'correct':state[q.id]?'wrong':''}">${q.id}</button>`).join('');grid.querySelectorAll('button').forEach(b=>b.onclick=()=>open(Number(b.dataset.challengeId)))}
function progress(){const solved=Object.values(state).filter(x=>x.correct).length;document.getElementById('challengeSolved').textContent=solved;document.getElementById('challengeProgressBar').style.width=`${solved/10}%`}
function render(){const q=questions[current-1],attempt=state[current];const input=q.options?`<div class="challenge-options">${q.options.map((o,i)=>`<label><input type="radio" name="challengeAnswer" value="${o}" ${attempt?.value===o?'checked':''}><span>${i+1}. ${o}</span></label>`).join('')}</div>`:`<input class="challenge-answer-input" id="challengeAnswerInput" value="${attempt?.value||''}" autocomplete="off" placeholder="답을 입력하세요">`;document.getElementById('challengeProblem').innerHTML=`<div class="problem-meta"><span>문제 ${q.id}</span><span>${q.week}주차</span><span>${q.topic}</span><span class="difficulty ${q.difficulty}">${q.difficulty}</span><span class="source-badge ${q.sourceType.replace(' ','-')}">${q.source}</span></div><h2>${q.prompt}</h2><div class="challenge-answer-area">${input}<button class="primary-button" id="challengeSubmit">채점하기</button></div><div class="challenge-feedback ${attempt?(attempt.correct?'correct':'wrong'):''}" ${attempt?'':'hidden'}><strong>${attempt?.correct?'정답입니다':'다시 확인해 보세요'}</strong><p>${q.explanation}</p><span>정답: ${q.answer}</span></div><div class="challenge-nav"><button class="text-button" id="challengePrev" ${current===1?'disabled':''}>← 이전</button><button class="text-button" id="challengeNext" ${current===1000?'disabled':''}>다음 →</button></div>`;document.getElementById('challengeSubmit').onclick=submit;document.getElementById('challengePrev').onclick=()=>open(current-1);document.getElementById('challengeNext').onclick=()=>open(current+1);document.getElementById('challengeAnswerInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')submit()});renderIndex();progress()}
function submit(){const q=questions[current-1];const value=q.options?document.querySelector('input[name="challengeAnswer"]:checked')?.value:document.getElementById('challengeAnswerInput')?.value;if(value==null||!String(value).trim())return;state[current]={value:String(value),correct:normalize(value)===normalize(q.answer)};save();render()}
function open(id,sync=true){current=Math.max(1,Math.min(1000,id||1));save();if(sync&&location.hash!==`#/challenge/${current}`)history.pushState(null,'',`#/challenge/${current}`);render()}
function openFromRoute(){initFilters();filter();const match=location.hash.match(/^#\/challenge\/(\d+)$/);open(match?Number(match[1]):current,false)}
window.challengeBank=questions;
window.challengeApp={open,openFromRoute};
})();
