(function(){
'use strict';
const bank=window.challengeBank, advanced=window.advancedProblems;
const roman=['I','II','III','IV','V','VI','VII','VIII','IX','X'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rich=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>');
const read=(k,f)=>{try{return JSON.parse(window.studyStore.getItem(k))||f}catch{return f}};
const write=(k,v)=>{try{window.studyStore.setItem(k,JSON.stringify(v))}catch{}};
const state=Object.fromEntries(bank.map(q=>[q.id,read('exam-'+q.uid,{})])),advancedState=read('challenge-advanced-state-v1',{});
window.questionMaterial=q=>{let material=q.visual||'';if(q.materialImage)material='<img class="assignment-material" src="'+esc(q.materialImage)+'" alt="문제 그림" />';if(q.code)material+='<pre class="exam-code">'+esc(q.code)+'</pre>';if(q.table)material+='<table class="exam-table">'+q.table.map((r,i)=>'<tr>'+r.map(x=>'<'+(i?'td':'th')+'>'+esc(x)+'</'+(i?'td':'th')+'>').join('')+'</tr>').join('')+'</table>';if(q.referenceImage)material+='<details class="instruction-reference"><summary>Pep/8 명령어 표</summary><img src="'+esc(q.referenceImage)+'" alt="Pep/8 명령어 표"></details>';return material+window.originalReference(q);};
window.originalReference=q=>{const images=q.originalImages?.length?q.originalImages:q.originalImage?[{image:q.originalImage,label:q.source}]:[];if(!images.length)return '';return `<details class="instruction-reference original-reference"><summary>기출 원문 보기</summary>${images.map(ref=>`<figure>${images.length>1?`<figcaption>${esc(ref.label)}</figcaption>`:''}<a href="${esc(ref.image)}" target="_blank" rel="noopener" aria-label="${esc(ref.label)} 원문 확대"><img loading="lazy" src="${esc(ref.image)}" alt="${esc(ref.label)} 원문"></a></figure>`).join('')}</details>`;};
let current=1,isAdvanced=false,filtered=bank;
// Exported for the independent full-bank audit; never labels semantic checks as passed.
window.examAudit=()=>{const seen=new Map();return bank.map(q=>{const duplicateOf=seen.get(q.prompt)||null;if(!duplicateOf)seen.set(q.prompt,q.id);return{id:q.id,week:q.week,duplicateOf,prompt:q.prompt,source:q.source,visual:!!q.visual,semanticReview:q.review?.status||'original-reference',issues:[...(duplicateOf?['동일 지문 반복']:[]),...(/최소 비트 수/.test(q.prompt)?['계산 검증 필요']:[])]}})};
const gate=(kind)=>{
 const shapes={AND:'M160 50 L205 50 A40 40 0 0 1 205 130 L160 130 Z',OR:'M150 50 Q185 90 150 130 Q220 135 250 90 Q220 45 150 50 Z',XOR:'M160 50 Q195 90 160 130 Q230 135 260 90 Q230 45 160 50 Z',NOT:'M160 50 L235 90 L160 130 Z'};
 const end=kind==='XOR'?260:kind==='OR'?250:245;
 return `<svg viewBox="0 0 420 180" role="img" aria-label="입력과 출력이 표시된 논리 게이트 기호"><g fill="none" stroke="currentColor" stroke-width="2.5"><path d="${shapes[kind]}"/>${kind==='XOR'?'<path d="M150 50 Q185 90 150 130"/>':''}${kind==='NOT'?'<circle cx="240" cy="90" r="5"/><path d="M75 90 H160"/>':'<path d="M75 70 H167 M75 110 H167"/>'}<path d="M${end} 90 H335"/></g><g font-size="18" fill="currentColor"><text x="45" y="${kind==='NOT'?96:76}">A</text>${kind==='NOT'?'':'<text x="45" y="116">B</text>'}<text x="348" y="96">Y</text></g></svg>`;
};
const block=(name,inputs)=>`<svg viewBox="0 0 520 200" role="img" aria-label="${esc(name)} 입출력 블록도"><g fill="none" stroke="currentColor" stroke-width="2"><rect x="185" y="25" width="150" height="145"/>${inputs.map((x,i)=>`<path d="M90 ${55+i*35} H185"/>`).join('')}<path d="M335 65 H435 M335 135 H435"/></g><g fill="currentColor" font-size="18"><text x="260" y="105" text-anchor="middle">${esc(name)}</text>${inputs.map((x,i)=>`<text x="35" y="${61+i*35}">${esc(x)}</text>`).join('')}<text x="447" y="71">Q</text><text x="447" y="141">Q̅</text></g></svg>`;
const ripple=`<svg viewBox="0 0 580 200" role="img" aria-label="전가산기 네 개의 캐리가 차례로 전달되는 4비트 리플 캐리 가산기"><g fill="none" stroke="currentColor" stroke-width="2">${[0,1,2,3].map(i=>`<rect x="${80+i*120}" y="60" width="80" height="70"/><path d="M${40+i*120} 95 H${80+i*120} M${105+i*120} 30 V60 M${135+i*120} 30 V60 M${120+i*120} 130 V170"/>`).join('')}<path d="M520 95 H560"/></g><g font-size="17" fill="currentColor">${[0,1,2,3].map(i=>`<text x="${91+i*120}" y="102">FA ${i}</text><text x="${95+i*120}" y="23">A${i}</text><text x="${130+i*120}" y="23">B${i}</text><text x="${110+i*120}" y="191">S${i}</text>`).join('')}<text x="8" y="90">C₀</text><text x="541" y="85">C₄</text></g></svg>`;
const counter=`<svg viewBox="0 0 620 180" role="img" aria-label="하강 에지 T 플립플롭 3개가 Q에서 다음 클록으로 연결된 비동기 카운터"><g fill="none" stroke="currentColor" stroke-width="2">${[0,1,2].map(i=>`<rect x="${85+i*175}" y="40" width="100" height="90"/><circle cx="${80+i*175}" cy="105" r="5"/><path d="M${85+i*175} 95 L${95+i*175} 105 L${85+i*175} 115 M${130+i*175} 20 V40 M${185+i*175} 75 H${210+i*175} ${i<2?`V105 H${250+i*175}`:''}"/>`).join('')}<path d="M15 105 H75"/></g><g fill="currentColor" font-size="17">${[0,1,2].map(i=>`<text x="${105+i*175}" y="17">T=1</text><text x="${116+i*175}" y="82">T-FF</text><text x="${190+i*175}" y="65">Q${i}</text>`).join('')}<text x="12" y="95">CLK</text></g></svg>`;
for(const q of bank){
 if(['original','textbook-adaptation','historical-original','reviewed-textbook','reviewed-exam-adaptation'].includes(q.provenance?.kind))continue;
 // Prior source badges were assigned by index, not provenance. Do not retain false attribution.
 if(!q.provenance&&q.sourceType!=='기출'){q.source='자체 제작';q.sourceType='직접 제작'}else if(!q.provenance){q.source=q.source.replace(' 기출',' · 변형');q.sourceType='기출 변형'}
 if(/16진수 .*최소 비트 수/.test(q.prompt)){const hex=q.prompt.match(/16진수 (\w+)/)[1];q.answer=parseInt(hex,16).toString(2).length+'';q.explanation=`선행 0을 제외한 ${parseInt(hex,16).toString(2)}의 길이는 ${q.answer}비트이다.`}
 if(q.topic==='논리회로' && q.options && ['AND','OR','NOT','XOR'].includes(q.answer)){q.visual=gate(q.answer);q.prompt='다음 기호가 나타내는 논리 게이트의 이름을 쓰시오.';delete q.options}
 if(q.topic==='순서논리회로'){
  const name=['SR 래치','D 플립플롭','JK 플립플롭','T 플립플롭','비동기 카운터'].find(x=>q.prompt.includes(x)||q.answer===x);
  // Type-identification questions use an unlabelled block to avoid revealing the answer.
  q.visual=name==='비동기 카운터'?counter:block('순서회로',name==='SR 래치'?['S','R']:name==='JK 플립플롭'?['J','K','CLK']:name==='D 플립플롭'?['D','CLK']:['T','CLK']);
 }
 if(q.prompt.includes('SR 래치에서 일반적으로')){q.prompt='NOR 게이트로 구성한 active-high SR 래치에서 금지되는 입력을 S,R 순서로 쓰시오.';q.visual=block('SR 래치',['S','R'])}
 if(q.topic==='논리회로'&&!q.visual){
  if(q.prompt.includes('ripple-carry'))q.visual=ripple;
  else if(q.prompt.includes('소수'))q.visual='<table class="exam-table"><caption>3비트 입력</caption><thead><tr><th>B₂</th><th>B₁</th><th>B₀</th><th>소수 여부</th></tr></thead><tbody>'+Array.from({length:8},(_,i)=>'<tr>'+i.toString(2).padStart(3,'0').split('').map(b=>'<td>'+b+'</td>').join('')+'<td>?</td></tr>').join('')+'</tbody></table>';
  else q.visual='<svg viewBox="0 0 560 180" role="img" aria-label="A OR B 결과 두 개와 NOT A 결과가 AND 게이트로 연결됨"><g stroke="currentColor" stroke-width="2" fill="none"><rect x="130" y="35" width="100" height="45"/><rect x="130" y="110" width="100" height="45"/><rect x="370" y="45" width="90" height="100"/><path d="M55 45 H130 M55 70 H130 M55 133 H130 M230 57 H290 V65 H370 M290 65 V125 H370 M230 133 H275 V95 H370 M460 95 H510"/></g><g fill="currentColor" font-size="18"><text x="15" y="49">A=0</text><text x="15" y="78">B=1</text><text x="15" y="139">A=0</text><text x="164" y="64">OR</text><text x="160" y="139">NOT</text><text x="390" y="103">AND</text><text x="520" y="100">Y</text></g></svg>';
 }
}
function navigate(n,adv=false,sync=true){isAdvanced=adv;current=Math.max(1,Math.min(adv?advanced.length:bank.length,Number(n)||1));if(sync)history.pushState(null,'',adv?`#/challenge/advanced/${current}`:`#/challenge/${current}`);render();}
function init(){const topic=document.getElementById('challengeTopic');if(!topic)return;topic.innerHTML='<option value="all">전체</option>'+[...new Set(bank.map(q=>q.topic))].map(t=>`<option>${esc(t)}</option>`).join('');for(const id of ['challengeWeek','challengeTopic','challengeDifficulty','challengeSource','challengeStatus'])document.getElementById(id).onchange=()=>{filter();if(!isAdvanced&&filtered.length&&!filtered.some(q=>q.id===current))navigate(filtered[0].id);else if(!isAdvanced&&!filtered.length){document.getElementById('challengeProblem').innerHTML='<div class="problem-empty"><h2>조건에 맞는 문제가 없습니다.</h2><p>필터를 변경해 주세요.</p></div>';renderIndex()}else render()};document.getElementById('challengeRandom').onclick=()=>{filter();if(filtered.length)navigate(filtered[Math.floor(Math.random()*filtered.length)].id)};filter()}
function filter(){const val=id=>document.getElementById(id).value;filtered=bank.filter(q=>(val('challengeWeek')==='all'||q.week===+val('challengeWeek'))&&(val('challengeTopic')==='all'||q.topic===val('challengeTopic'))&&(val('challengeDifficulty')==='all'||q.difficulty===val('challengeDifficulty'))&&(val('challengeSource')==='all'||q.sourceType===val('challengeSource'))&&(val('challengeStatus')==='all'||val('challengeStatus')==='unsolved'&&!state[q.id]?.checked||val('challengeStatus')==='correct'&&state[q.id]?.correct||val('challengeStatus')==='wrong'&&state[q.id]?.checked&&!state[q.id]?.correct));document.getElementById('challengeCount').textContent=filtered.length+'개'}
function renderIndex(){const grid=document.getElementById('challengeNumberGrid');grid.innerHTML=filtered.length?filtered.map(q=>`<button type="button" aria-label="문제 ${q.id}" aria-current="${!isAdvanced&&q.id===current?'true':'false'}" class="${!isAdvanced&&q.id===current?'current':''} ${state[q.id]?.correct?'correct':''}" data-id="${q.id}">${q.id}</button>`).join(''):'<p class="empty-results" role="status">조건에 맞는 문제가 없습니다.</p>';grid.querySelectorAll('button').forEach(b=>b.onclick=()=>navigate(b.dataset.id));const extra=document.getElementById('advancedNumbers');extra.innerHTML=roman.map((r,i)=>`<button aria-label="심화 ${r}" aria-current="${isAdvanced&&current===i+1?'true':'false'}" class="${isAdvanced&&current===i+1?'current':''}" data-id="${i+1}">${r}</button>`).join('');extra.querySelectorAll('button').forEach(b=>b.onclick=()=>navigate(b.dataset.id,true));const solved=Object.values(state).filter(s=>s.correct).length;document.getElementById('challengeSolved').textContent=solved;document.getElementById('challengeProgressBar').style.width=solved/bank.length*100+'%'}
function render(){window.studyStore.visit?.(location.hash);const q=isAdvanced?advanced[current-1]:bank[current-1],s=state[current]||{};let prompt=q.prompt,material=q.visual||'';
 if(q.materialImage)material=`<a class="original-question-link" href="${q.materialImage}" target="_blank" rel="noopener" aria-label="${esc(q.source)} 원문 크게 보기"><img class="original-question" src="${q.materialImage}" alt="${esc(q.source+' '+q.prompt)}" width="${q.width}" height="${q.height}"></a>`;
 if(q.code)material+='<pre class="exam-code">'+esc(q.code)+'</pre>';if(q.table)material+='<table class="exam-table"><thead><tr>'+q.table[0].map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+q.table.slice(1).map(row=>'<tr>'+row.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
 const manual=isAdvanced||q.grading==='self';
 if(isAdvanced&&current===4){prompt='프로그램이 0x0000부터 시작한다. 다음 Pep/8 코드를 실행한 후 출력되는 문자를 구하고, 변경되는 명령어와 A의 값을 추적하시오.';material='<pre class="exam-code">주소    바이트\n0000    D1 00 1D\n0003    F1 00 09\n0006    C1 00 17\n0009    71 00 19\n000C    A1 00 1B\n000F    F1 00 16\n0012    51 00 16\n0015    00\n0016    00\n0017    00 05\n0019    00 03\n001B    00 30\n001D    81</pre>'}
 const node=document.getElementById('challengeProblem');node.innerHTML=`<div class="problem-meta"><span>${isAdvanced?'심화 '+roman[current-1]:'문제 '+current}</span>${isAdvanced?'':`<span>${q.week}주차</span>`}<span>${esc(q.topic)}</span><span class="difficulty">${isAdvanced?'심화':esc(q.difficulty)}</span>${q.source&&q.source!=='자체 제작'&&q.sourceType!=='직접 제작'&&q.type!=='직접 제작'?`<span class="source-badge" title="${esc(q.provenance?.basis||q.source)}">${esc(q.source)}</span>`:''}</div><h2 tabindex="-1">${rich(prompt)}</h2>${material?`<figure class="exam-material ${q.materialImage?'original-material':''}">${material}${q.materialImage?'<figcaption>원문을 누르면 크게 볼 수 있어요.</figcaption>':''}</figure>`:''}${q.referenceImage?`<details class="instruction-reference"><summary>Pep/8 명령어 표</summary><a href="${q.referenceImage}" target="_blank" rel="noopener"><img src="${q.referenceImage}" alt="기말고사에 제공된 Pep/8 명령어 표"></a></details>`:''}${window.originalReference(q)}<div class="challenge-answer-area"><label for="examAnswer">${isAdvanced?'풀이':'답안'}</label>${!isAdvanced&&q.options?`<div class="challenge-options">${q.options.map((o,i)=>`<label><input type="radio" name="examOption" value="${esc(o)}" ${s.value===o?'checked':''}><span>${i+1}. ${esc(o)}</span></label>`).join('')}</div>`:'<textarea id="examAnswer" class="challenge-answer-input" rows="'+(isAdvanced?7:3)+'"></textarea>'}<div class="exam-actions">${manual?'':'<button id="examSubmit" class="primary-button">채점</button>'}<button id="examReveal" class="answer-toggle" aria-expanded="false">${manual?'예시 답안':'정답·해설'}</button></div><p id="examResult" role="status"></p><section id="examSolution" hidden><h3>${manual?'예시 답안':'정답'}</h3><p>${rich(q.answer)}</p>${q.explanation?`<p>${rich(q.explanation)}</p>`:''}${!isAdvanced&&manual?'<div class="self-review"><p>풀이를 비교한 뒤 표시해 주세요.</p><button id="examSelfCorrect" class="text-button">맞았어요</button><button id="examSelfRetry" class="text-button">다시 풀기</button></div>':''}</section></div><div class="challenge-nav"><button class="text-button" id="examPrev" ${current===1?'disabled':''}>이전</button><button class="text-button" id="examNext" ${current===(isAdvanced?advanced.length:bank.length)?'disabled':''}>다음</button></div>`;
 const field=document.getElementById('examAnswer');if(field){field.value=isAdvanced?(advancedState[current-1]||''):(s.value||'');field.oninput=()=>{if(isAdvanced){advancedState[current-1]=field.value;write('challenge-advanced-state-v1',advancedState)}else{state[current]={value:field.value};write('exam-'+bank[current-1].uid,state[current])}}}
 document.getElementById('examReveal').onclick=e=>{const solution=document.getElementById('examSolution');solution.hidden=!solution.hidden;e.target.setAttribute('aria-expanded',!solution.hidden)};
 if(!isAdvanced&&manual){const mark=correct=>{const value=field?.value||'';if(!value.trim()){document.getElementById('examResult').textContent='답안을 입력한 뒤 확인해 주세요.';return}state[current]={value,correct,checked:true,selfAssessed:true};write('exam-'+bank[current-1].uid,state[current]);document.getElementById('examResult').textContent=correct?'맞은 문제로 표시했어요.':'다시 풀 문제로 표시했어요.';filter();renderIndex()};document.getElementById('examSelfCorrect').onclick=()=>mark(true);document.getElementById('examSelfRetry').onclick=()=>mark(false)}
 const submit=document.getElementById('examSubmit');if(submit)submit.onclick=()=>{const value=q.options?document.querySelector('input[name="examOption"]:checked')?.value:field.value;const status=document.getElementById('examResult');if(!value?.trim()){status.textContent='답안을 입력하세요.';return}const norm=v=>v.trim().replace(/\s+/g,'').toUpperCase();const correct=norm(value)===norm(q.answer);state[current]={value,correct,checked:true};write('exam-'+bank[current-1].uid,state[current]);status.textContent=correct?'정답입니다.':'정답·해설을 확인하세요.';filter();renderIndex()};document.getElementById('examPrev').onclick=()=>navigate(current-1,isAdvanced);document.getElementById('examNext').onclick=()=>navigate(current+1,isAdvanced);renderIndex();}
window.challengeApp={open:(n,sync=true)=>navigate(n,false,sync),openFromRoute:()=>{init();const a=location.hash.match(/^#\/challenge\/advanced\/(\d+)$/),n=location.hash.match(/^#\/challenge\/(\d+)$/);navigate(a?+a[1]:n?+n[1]:1,!!a,false)}};
})();
